import { Navbar } from '@/components/Navbar'
import { DataProvider } from '@/context/DataContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Auditoria Interna',
  description: 'Generated by Comfama',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-comfama.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href={inter.url} rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <Navbar />
        <DataProvider>
            {children}
        </DataProvider>
      </body>
    </html>
  )
}
